### ISSUE TITLE
System.NullReferenceException throwd when initialize ExtendedConsole Class 

### ISSUE THREAD

**Issue by JasonHeee** [replaysMike/AnyConsole#6]
var console = new ExtendedConsole();
System.NullReferenceException: 'Object reference not set to an instance of an object.'

My Windows OS is WIN7 and visual studio is vs2017

**Comment by replaysMike** [comment]
Thanks for the report! I’ll get this fixed right away.

**Comment by replaysMike** [comment]
@JasonHeee this is now fixed as of version 1.0.34

**Comment by JasonHeee** [comment]
thanks !@replaysMike
